FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

LABEL maintainer="Ömercan Yazici" \
      description="Anydsl Meta package with CUDA 12.2 GPU support" \
      version="0.1.1"

ENV DEBIAN_FRONTEND noninteractive
ENV CUDAToolkit_LIBRARY_ROOT /usr/local/cuda

RUN apt-get update && apt-get install -y build-essential wget g++ git subversion zlib1g-dev cmake ninja-build python3 && rm -rf /var/lib/apt/lists/* 

WORKDIR /
COPY compile.sh /compile.sh
COPY config-cuda.sh /config.sh
RUN bash /compile.sh && rm /compile.sh && rm /config.sh
