FROM gcc:13-bookworm

LABEL maintainer="Ömercan Yazici" \
      description="Anydsl Meta package without GPU support" \
      version="0.1.1"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y git subversion cmake ninja-build && rm -rf /var/lib/apt/lists/* 

WORKDIR /
COPY compile.sh /compile.sh
COPY config-cpu.sh /config.sh
RUN bash /compile.sh && rm /compile.sh && rm /config.sh