FROM pearcoding/anydsl:latest-cuda-jit

LABEL maintainer="Ömercan Yazici" \
      description="Ignis Raytracer with AVX2 & CUDA backend" \
      version="0.2.0"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y libeigen3-dev libtbb-dev libsdl2-dev && rm -rf /var/lib/apt/lists/* 

COPY . /ignis
WORKDIR /ignis
RUN ./docker/compile.sh
ENV LD_LIBRARY_PATH="/anydsl/runtime/build/lib:${LD_LIBRARY_PATH}"

ENTRYPOINT [ "igview", "/ignis/scenes/diamond_scene.json" ]
