find_package(bash-completion QUIET)
if(BASH_COMPLETION_FOUND AND CMAKE_INSTALL_PREFIX)
    set(BASH_COMPLETION_COMPLETIONS_DIR "${CMAKE_INSTALL_PREFIX}/share/bash-completion/completions" CACHE PATH "Directory bash-completion is installed to")
    message(STATUS "Bash-completion will be installed to: ${BASH_COMPLETION_COMPLETIONS_DIR}")
    install(FILES "${CMAKE_SOURCE_DIR}/scripts/bash/ignis-completion.bash" DESTINATION "${BASH_COMPLETION_COMPLETIONS_DIR}/" EXCLUDE_FROM_ALL)
endif()
