set(CPACK_NSIS_MODIFY_PATH ON)
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
set(CPACK_NSIS_COMPRESSOR "/SOLID lzma \r\n SetCompressorDictSize 32")
if( CMAKE_CL_64 )
  if(NOT DEFINED CPACK_NSIS_INSTALL_ROOT)
    set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
  endif()
endif()

if(WIN32 AND NOT UNIX)
  if(NOT DEFINED CPACK_PACKAGE_INSTALL_REGISTRY_KEY)
    set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "IGNIS")
  endif()
endif()

set(CPACK_NSIS_MENU_LINKS "${Ignis_URL}" "${PROJECT_NAME} on Github")

set(CPACK_NSIS_INSTALLED_ICON_NAME $<TARGET_FILE:igexplorer>)

set(CPACK_NSIS_URL_INFO_ABOUT "${Ignis_URL}")
set(CPACK_NSIS_HELP_LINK "${Ignis_URL}")