ARG IG_DIR=.
FROM pearcoding/anydsl:latest-cpu-jit as build

LABEL maintainer="Ömercan Yazici" \
      description="Ignis Raytracer without GPU support" \
      version="0.2.0"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y libtbb-dev libsdl2-dev libpython3-dev && rm -rf /var/lib/apt/lists/* 

COPY $IG_DIR /ignis
WORKDIR /ignis
RUN ./scripts/docker/ignis/compile.sh

FROM gcc:12 as runtime

LABEL maintainer="Ömercan Yazici" \
      description="Ignis Raytracer without GPU support" \
      version="0.2.0"

ENV DEBIAN_FRONTEND noninteractive

COPY --from=build /ignis-install/ /usr/
COPY --from=build /anydsl/artic/build/lib/libartic.so /anydsl/thorin/build/lib/libthorin.so /anydsl/runtime/build/lib/libruntime.so /anydsl/runtime/build/lib/libruntime_jit_artic.so /anydsl/llvm_install/lib/libLLVM-14.so /usr/lib/

RUN apt-get update && apt-get install -y libtbb2 libsdl2-2.0-0 libgomp1 libxml2 python3 && rm -rf /var/lib/apt/lists/* 

ENTRYPOINT [ "igcli" ]
