FROM pearcoding/anydsl:latest-cuda-jit as build

LABEL maintainer="Ömercan Yazici" \
      description="Ignis Raytracer with CUDA GPU support" \
      version="0.2.0"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y libeigen3-dev libtbb-dev libsdl2-dev && rm -rf /var/lib/apt/lists/* 

ENV LD_LIBRARY_PATH="/usr/local/cuda/compat:${LD_LIBRARY_PATH}"
COPY . /ignis
WORKDIR /ignis
RUN ./scripts/docker/ignis/compile.sh

FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04 as runtime

LABEL maintainer="Ömercan Yazici" \
      description="Ignis Raytracer with CUDA GPU support" \
      version="0.2.0"

ENV DEBIAN_FRONTEND noninteractive

COPY --from=build /ignis-install/ /usr/
COPY --from=build /usr/local/cuda/nvvm/ /usr/local/cuda/nvvm/
COPY --from=build /anydsl/artic/build/lib/libartic.so /anydsl/thorin/build/lib/libthorin.so /anydsl/runtime/build/lib/libruntime.so /anydsl/runtime/build/lib/libruntime_jit_artic.so /anydsl/llvm_install/lib/libLLVM-14.so /usr/lib/

RUN apt-get update && apt-get install -y libtbb2 libsdl2-2.0-0 libgomp1 libxml2 && rm -rf /var/lib/apt/lists/* 

ENTRYPOINT [ "igcli" ]
