ARG IG_DIR=.
FROM pearcoding/anydsl:latest-cpu-jit as build

LABEL maintainer="Ömercan Yazici" \
      description="Ignis Raytracer - Test CI version. Not indended for deployment" \
      version="0.2.1"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y libtbb-dev libsdl2-dev libpython3-dev && rm -rf /var/lib/apt/lists/* 

COPY $IG_DIR /ignis
WORKDIR /ignis
RUN bash ./scripts/docker/ignis/compile-test.sh
