name: Development (Docker)

on:
  push:
    branches: [ development ]
  pull_request:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: pearcoding/ignis

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      
      # Build Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./scripts/docker/ignis/Dockerfile-Test
          push: false
